/** Données de contenu QuizMoi — source pour Firestore (collection content/app). */

export const DEFAULT_COUNT = 8;

export const DEFAULT_THEMES = ["gouts", "amitie", "fun"];

export const QUIZ_TEMPLATES = [
  { id: "couple", icon: "💕", label: "Quiz couple", desc: "Amour & souvenirs", themes: ["amour", "souvenirs"], count: 10 },
  { id: "bff", icon: "💛", label: "Quiz BFF", desc: "Amitié & fun", themes: ["amitie", "fun"], count: 10 },
  { id: "famille", icon: "👨‍👩‍👧", label: "Quiz famille", desc: "Famille & traditions", themes: ["famille", "souvenirs"], count: 8 },
  { id: "foodie", icon: "🍕", label: "Quiz food", desc: "Plats & goûts", themes: ["food", "gouts"], count: 8 },
];

export const THEMES = [
  { id: "gouts", icon: "🎯", label: "Goûts & style", desc: "Couleurs, mode, emoji…" },
  { id: "food", icon: "🍕", label: "Food & boisson", desc: "Plats, restos, cuisine…" },
  { id: "musique", icon: "🎵", label: "Musique & culture", desc: "Artistes, films, séries…" },
  { id: "amitie", icon: "💛", label: "Amitié", desc: "Entre nous, nos habitudes…" },
  { id: "amour", icon: "💕", label: "Amour & couple", desc: "Dates, cadeaux, romance…" },
  { id: "famille", icon: "👨‍👩‍👧", label: "Famille", desc: "Parents, fratrie, traditions…" },
  { id: "fun", icon: "😂", label: "Fun & personnalité", desc: "Défauts, peurs, super-pouvoirs…" },
  { id: "habitudes", icon: "⚡", label: "Habitudes", desc: "Matin, sport, sommeil…" },
  { id: "souvenirs", icon: "📸", label: "Souvenirs", desc: "Voyages, école, moments…" },
];

export const QUESTION_BANK = {
  gouts: [
    { text: "Ma couleur préférée ?", options: ["Bleu", "Rouge", "Vert", "Violet"] },
    { text: "Mon emoji signature ?", options: ["😎", "🔥", "✨", "💀"] },
    { text: "Mon style vestimentaire ?", options: ["Casual", "Sport", "Chic", "Streetwear"] },
    { text: "Ma saison préférée ?", options: ["Printemps", "Été", "Automne", "Hiver"] },
    { text: "Mon animal totem ?", options: ["Chat", "Chien", "Loup", "Panda"] },
    { text: "Ce que je collectionne ?", options: ["Rien", "Livres", "Sneakers", "Photos"] },
    { text: "Mon parfum / odeur favorite ?", options: ["Vanille", "Citron", "Boisé", "Floral"] },
    { text: "Mon accessoire fétiche ?", options: ["Montre", "Casquette", "Bijoux", "Sac"] },
    { text: "Ma marque préférée ?", options: ["Nike", "Zara", "Apple", "Aucune en vrai"] },
    { text: "Mon décor de chambre ?", options: ["Minimaliste", "Cosy", "Coloré", "Chaos organisé"] },
  ],
  food: [
    { text: "Mon plat préféré ?", options: ["Pizza", "Sushi", "Tacos", "Pâtes"] },
    { text: "Ma boisson préférée ?", options: ["Café", "Thé", "Jus", "Eau pétillante"] },
    { text: "Mon fast-food ?", options: ["McDo", "KFC", "Subway", "Burger maison"] },
    { text: "Mon dessert ultime ?", options: ["Gâteau", "Glace", "Tiramisu", "Crêpes"] },
    { text: "Mon snack tard le soir ?", options: ["Chips", "Chocolat", "Fruits", "Rien du tout"] },
    { text: "Mon type de cuisine ?", options: ["Italienne", "Asiatique", "Française", "Mexicaine"] },
    { text: "Comment je prends mon café ?", options: ["Noir", "Latté", "Cappuccino", "Je ne bois pas"] },
    { text: "Mon topping pizza ?", options: ["Pepperoni", "4 fromages", "Végétarienne", "Ananas"] },
    { text: "Mon resto préféré ?", options: ["Italien", "Sushi bar", "Brunch", "Street food"] },
    { text: "Mon plat à cuisiner ?", options: ["Pâtes", "Omelette", "Curry", "Je brûle tout"] },
  ],
  musique: [
    { text: "Mon style de musique ?", options: ["Pop", "Rap", "Rock", "Electro"] },
    { text: "Mon style d'artiste préféré ?", options: ["Rappeur", "Popstar", "Groupe de rock", "DJ / électro"] },
    { text: "Mon film préféré ?", options: ["Comédie", "Action", "Romance", "Horreur"] },
    { text: "Ma série du moment ?", options: ["Drama", "Comédie", "Thriller", "Animé"] },
    { text: "Mon endroit pour un concert ?", options: ["Stade", "Petite salle", "Festival", "Canapé"] },
    { text: "Mon genre YouTube ?", options: ["Humour", "Musique", "Gaming", "Vlogs"] },
    { text: "Mon réseau social préféré ?", options: ["TikTok", "Instagram", "Snap", "Aucun"] },
    { text: "Mon type de jeu vidéo ?", options: ["Sport", "Battle royale", "Aventure", "Je ne joue pas"] },
    { text: "Mon livre / manga ?", options: ["Roman", "BD", "Manga", "Je ne lis pas"] },
    { text: "Ma plateforme de streaming ?", options: ["Netflix", "Disney+", "Spotify", "YouTube"] },
  ],
  amitie: [
    { text: "Où on se retrouve le plus ?", options: ["Au café", "Chez moi", "En ville", "En ligne"] },
    { text: "Mon rôle dans le groupe ?", options: ["Le drôle", "Le sage", "L'organisateur", "Le fou"] },
    { text: "Comment je dis bonjour ?", options: ["La bise", "Le check", "Un cri", "Un message"] },
    { text: "Mon activité entre amis ?", options: ["Sortir", "Gaming", "Ciné", "Rien, on cause"] },
    { text: "Mon délire avec les potes ?", options: ["Blagues", "Memes", "Chansons", "Débats"] },
    { text: "Comment je réagis quand on m'appelle ?", options: ["Direct", "Je rappelle plus tard", "Message vocal", "Ghost 2h"] },
    { text: "Mon cadeau d'anniversaire idéal ?", options: ["Expérience", "Objet", "Argent", "Surprise"] },
    { text: "Mon groupe WhatsApp ?", options: ["Actif", "Muet", "Que des memes", "Plans de dernière minute"] },
    { text: "Mon meilleur ami sait que je…", options: ["Mange mal", "Dors tard", "Chante mal", "Procrastine"] },
    { text: "Notre inside joke ?", options: ["Un surnom", "Une phrase", "Un son", "Un regard"] },
  ],
  amour: [
    { text: "Mon date idéal ?", options: ["Resto", "Balade", "Ciné", "Netflix"] },
    { text: "Mon langage de l'amour ?", options: ["Cadeaux", "Temps", "Mots", "Câlins"] },
    { text: "Ma fleur préférée ?", options: ["Rose", "Tulipe", "Lys", "Aucune"] },
    { text: "Mon cadeau romantique ?", options: ["Lettre", "Bijou", "Surprise", "Repas maison"] },
    { text: "Ma chanson de couple ?", options: ["Slow", "Pop", "Rap", "On n'en a pas"] },
    { text: "Mon film romantique ?", options: ["Classique", "Comédie", "Drama", "Pas mon truc"] },
    { text: "Comment je dis je t'aime ?", options: ["Direct", "Par actions", "Par emoji", "Rarement"] },
    { text: "Mon endroit romantique ?", options: ["Plage", "Montagne", "Ville", "Chez nous"] },
    { text: "Mon petit-déjeuner en amoureux ?", options: ["Croissants", "Pancakes", "Fruits", "Café seulement"] },
    { text: "Ma soirée parfaite à deux ?", options: ["Resto", "Série", "Balade", "Soirée jeux"] },
  ],
  famille: [
    { text: "Mon plat de famille ?", options: ["Gratin", "Raclette", "Tajine", "Barbecue"] },
    { text: "Mon rôle en famille ?", options: ["Le calme", "Le boute-en-train", "Le mediator", "Le rebelle"] },
    { text: "Ma tradition familiale ?", options: ["Repas du dimanche", "Vacances", "Noël", "Aucune fixe"] },
    { text: "Qui je ressemble le plus ?", options: ["Maman", "Papa", "Personne", "Mon frère/sœur"] },
    { text: "Mon surnom en famille ?", options: ["Bébé", "Champion", "Le petit", "Aucun"] },
    { text: "Mon endroit chez les parents ?", options: ["Canapé", "Cuisine", "Ma chambre", "Jardin"] },
    { text: "Ce que ma famille dit toujours ?", options: ["Mange !", "Range !", "Tu dors ?", "Appelle plus"] },
    { text: "Mon cadeau pour Papa/Maman ?", options: ["Parfum", "Expérience", "Fait main", "Carte"] },
    { text: "Notre activité en famille ?", options: ["Jeux", "Balade", "Ciné", "On se dispute"] },
    { text: "Mon plat appris en famille ?", options: ["Gâteau", "Sauce", "Soupe", "Rien, Uber Eats"] },
  ],
  fun: [
    { text: "Mon pire défaut ?", options: ["Trop en retard", "Trop bavard", "Perfectionniste", "Distrait"] },
    { text: "Mon super-pouvoir secret ?", options: ["Dormir partout", "Manger énormément", "Retenir les dates", "Faire rire"] },
    { text: "Ma plus grande peur ?", options: ["Araignées", "Vide", "Examen oral", "Rater le réveil"] },
    { text: "Mon talent caché ?", options: ["Chant", "Dessin", "Imitations", "Aucun"] },
    { text: "Mon emoji quand je suis énervé ?", options: ["😤", "💀", "🙃", "🤐"] },
    { text: "Ma réaction au stress ?", options: ["Je mange", "Je dors", "Je parle", "Je disparais"] },
    { text: "Mon mensonge préféré ?", options: ["J'arrive", "5 minutes", "J'ai pas vu", "Demain je m'y mets"] },
    { text: "Mon délire absurde ?", options: ["Blagues nulles", "Voix bizarres", "Danses", "Théories"] },
    { text: "Mon personnage Disney ?", options: ["Princesse", "Méchant", "Sidekick", "Héros"] },
    { text: "Ce qui me fait rire à fond ?", options: ["Chutes", "Memes", "Blagues nulles", "Mes potes"] },
  ],
  habitudes: [
    { text: "Plutôt lève-tôt ou couche-tard ?", options: ["Lève-tôt", "Couche-tard", "Les deux", "Dépend"] },
    { text: "Mon sport ?", options: ["Foot", "Muscu", "Course", "Aucun"] },
    { text: "Mon rituel du matin ?", options: ["Café", "Douche", "Scroll", "Rien"] },
    { text: "Combien d'alarmes le matin ?", options: ["1", "3", "10", "Je n'ai pas besoin"] },
    { text: "Mon rangement ?", options: ["Impeccable", "Organisé", "Bordélique", "Chaos"] },
    { text: "Mon temps d'écran ?", options: ["Trop", "Normal", "Peu", "Je nie"] },
    { text: "Ma sieste ?", options: ["Tous les jours", "Week-end", "Jamais", "Au boulot en cachette"] },
    { text: "Mon moyen de transport ?", options: ["Voiture", "Vélo", "Transports", "À pied"] },
    { text: "Mon organisation ?", options: ["Agenda", "Listes", "Dans ma tête", "Aucune"] },
    { text: "Ma boisson du matin ?", options: ["Café", "Thé", "Jus", "Rien"] },
  ],
  souvenirs: [
    { text: "Mon meilleur voyage ?", options: ["Plage", "Montagne", "Ville", "Camping"] },
    { text: "Mon souvenir d'école ?", options: ["Rentrée", "Sortie", "Prof", "Récré"] },
    { text: "Mon moment le plus drôle ?", options: ["Soirée", "Vacances", "École", "Random"] },
    { text: "Mon cadeau le plus mémorable ?", options: ["Surprise", "Fait main", "Gadget", "Voyage"] },
    { text: "Mon endroit d'enfance ?", options: ["Parc", "Mer", "Campagne", "Ma chambre"] },
    { text: "Ma photo préférée ?", options: ["Entre amis", "En famille", "En voyage", "Selfie"] },
    { text: "Mon concert mémorable ?", options: ["Stade", "Petite salle", "Festival", "Jamais été"] },
    { text: "Mon anniversaire idéal ?", options: ["Grande fête", "Intime", "Surprise", "Discret"] },
    { text: "Mon souvenir avec toi ?", options: ["Une soirée", "Un voyage", "Une blague", "On se connaît pas assez"] },
    { text: "Mon objectif cette année ?", options: ["Voyage", "Sport", "Projet", "Profiter"] },
  ],
};

/** Quiz gamer prêts à jouer — 10 questions chacun (facile → difficile). */
export const GAMER_QUIZZES = [
  {
    id: "roblox",
    icon: "🟥",
    label: "Roblox",
    tag: "Sandbox · MMO",
    intro: "T'es un vrai Robloxien ? 10 questions de noob à pro.",
    questions: [
      { text: "Quelle monnaie achète-t-on avec de l'argent réel sur Roblox ?", options: ["Robux", "V-Bucks", "Coins", "Gems"], correct: 0 },
      { text: "Comment s'appelle l'outil pour créer des jeux Roblox ?", options: ["Roblox Studio", "Unity Roblox", "Block Builder", "GameCraft"], correct: 0 },
      { text: "Quel langage de script utilise Roblox Studio ?", options: ["Lua", "Python", "JavaScript", "C++"], correct: 0 },
      { text: "En quelle année Roblox est-il sorti officiellement ?", options: ["2006", "2010", "2012", "2015"], correct: 0 },
      { text: "Comment s'appelait Roblox à l'origine ?", options: ["DynaBlocks", "BlockWorld", "MiniVerse", "CubeLand"], correct: 0 },
      { text: "Quel jeu Roblox est célèbre pour adopter des animaux ?", options: ["Adopt Me!", "Pet Simulator", "Brookhaven", "Jailbreak"], correct: 0 },
      { text: "Que signifie « OOF » dans la culture Roblox ?", options: ["Son de mort / meme", "Victoire", "Achat premium", "Nom de monnaie"], correct: 0 },
      { text: "Quel objet permet d'échanger des items limités entre joueurs ?", options: ["Le trading (échange)", "Le chat vocal", "Le Bounty", "Le VIP server"], correct: 0 },
      { text: "Qui est le fondateur de Roblox avec David Baszucki ?", options: ["Erik Cassel", "Elon Musk", "Gabe Newell", "Tim Sweeney"], correct: 0 },
      { text: "Combien de joueurs simultanés Roblox a-t-il dépassé (record mondial) ?", options: ["Plus de 40 millions", "500 000", "2 millions", "100 000"], correct: 0 },
    ],
  },
  {
    id: "brawlstars",
    icon: "⭐",
    label: "Brawl Stars",
    tag: "MOBA · Supercell",
    intro: "Shelly ou pro ? Prouve ta culture Brawl Stars.",
    questions: [
      { text: "Quel studio a développé Brawl Stars ?", options: ["Supercell", "Epic Games", "Riot Games", "Ubisoft"], correct: 0 },
      { text: "Quel est le premier brawler que tout le monde possède ?", options: ["Shelly", "Colt", "Nita", "Bull"], correct: 0 },
      { text: "Quelle monnaie premium achète le Brawl Pass ?", options: ["Gems", "Robux", "Credits", "Tokens"], correct: 0 },
      { text: "Quel mode consiste à collecter des gemmes au centre ?", options: ["Gem Grab", "Showdown", "Heist", "Bounty"], correct: 0 },
      { text: "Quel brawler est un sniper à longue portée avec des roses ?", options: ["Piper", "Bull", "El Primo", "Frank"], correct: 0 },
      { text: "Quel brawler lance deux revolvers ?", options: ["Colt", "Rico", "Brock", "Darryl"], correct: 0 },
      { text: "Quel brawler devient invisible dans un nuage de fumée ?", options: ["Leon", "Crow", "Spike", "Tara"], correct: 0 },
      { text: "Combien de joueurs par équipe en mode Gem Grab ?", options: ["3", "2", "4", "5"], correct: 0 },
      { text: "Comment s'appelle le compteur de progression des trophées d'un brawler ?", options: ["Trophées", "XP Steam", "Ligue FIFA", "Rank Valorant"], correct: 0 },
      { text: "Quel brawler est un luchador qui charge en mêlée ?", options: ["El Primo", "Poco", "Gene", "Byron"], correct: 0 },
    ],
  },
  {
    id: "gta5",
    icon: "🚗",
    label: "GTA 5",
    tag: "Action · Open world",
    intro: "Los Santos t'attend. 10 questions sur GTA V.",
    questions: [
      { text: "Dans quelle ville fictive se passe GTA 5 ?", options: ["Los Santos", "Liberty City", "Vice City", "San Fierro"], correct: 0 },
      { text: "Combien de protagonistes jouables en solo ?", options: ["3", "1", "2", "4"], correct: 0 },
      { text: "Quel personnage est un expert en braquages retraité ?", options: ["Michael", "Franklin", "Trevor", "Lamar"], correct: 0 },
      { text: "Quel personnage vit à Sandy Shores et est très instable ?", options: ["Trevor", "Michael", "Franklin", "Lester"], correct: 0 },
      { text: "Comment s'appelle le chien de Franklin ?", options: ["Chop", "Rex", "Max", "Buddy"], correct: 0 },
      { text: "Quel studio développe la série GTA ?", options: ["Rockstar Games", "EA", "Activision", "Bethesda"], correct: 0 },
      { text: "Quel mode en ligne massif accompagne GTA 5 ?", options: ["GTA Online", "Red Dead Online", "San Andreas MP", "Los Santos RP seulement"], correct: 0 },
      { text: "Quel personnage guide les braquages depuis son sous-sol ?", options: ["Lester", "Simeon", "Devin", "Ron"], correct: 0 },
      { text: "Quelle est la première grosse mission de braquage (banque) ?", options: ["Fleeca", "Pacific Standard d'emblée", "Casino d'abord", "Union Depository en premier"], correct: 0 },
      { text: "Sur quelle ville réelle Los Santos est-elle basée ?", options: ["Los Angeles", "Miami", "Las Vegas", "Chicago"], correct: 0 },
    ],
  },
  {
    id: "fifa",
    icon: "⚽",
    label: "FIFA / EA FC",
    tag: "Sport · Football",
    intro: "Du kick-off à la Ligue des champions virtuelle.",
    questions: [
      { text: "Quel éditeur publie FIFA / EA Sports FC ?", options: ["EA Sports", "Konami", "2K", "Ubisoft"], correct: 0 },
      { text: "Comment s'appelle le mode où tu composes une équipe avec des cartes ?", options: ["Ultimate Team (FUT)", "Career Mode", "Volta", "Pro Clubs seulement"], correct: 0 },
      { text: "Que signifie la stat « PAC » sur une carte ?", options: ["Vitesse (Pace)", "Passe", "Physique", "Penalty"], correct: 0 },
      { text: "Combien de minutes dure un match standard (temps réglementaire) ?", options: ["90 minutes", "60 minutes", "45 minutes", "120 minutes"], correct: 0 },
      { text: "Quel bouton sert souvent à faire des gestes techniques (skills) ?", options: ["Stick droit", "Stick gauche seul", "D-pad haut", "Touchpad"], correct: 0 },
      { text: "Comment s'appelle le mode carrière où tu incarnes un joueur ?", options: ["Mode Joueur", "Mode Manager seulement", "Superstar KO", "Draft Battle"], correct: 0 },
      { text: "Quel mode compétitif en ligne hebdomadaire est très populaire en FUT ?", options: ["FUT Champions / Weekend League", "Survival Mode", "Zombies FC", "Kart League"], correct: 0 },
      { text: "Que mesure la « chimie » entre joueurs en FUT ?", options: ["Leur synergie en équipe", "Leur vitesse seule", "Leur prix sur le marché", "Leur âge réel"], correct: 0 },
      { text: "Quel type de tir est le « finesse shot » ?", options: ["Tir enroulé placé", "Tir de la tête", "Tacle glissé", "Coup franc défensif"], correct: 0 },
      { text: "Quel pays a accueilli la Coupe du Monde FIFA 2022 ?", options: ["Qatar", "Brésil", "France", "Russie"], correct: 0 },
    ],
  },
  {
    id: "fortnite",
    icon: "🪂",
    label: "Fortnite",
    tag: "Battle Royale",
    intro: "Battle Bus, builds et Victory Royale — t'en es où ?",
    questions: [
      { text: "Quel studio développe Fortnite ?", options: ["Epic Games", "Blizzard", "Valve", "Mojang"], correct: 0 },
      { text: "Combien de joueurs maximum en Battle Royale ?", options: ["100", "50", "32", "150"], correct: 0 },
      { text: "De quoi les joueurs sautent-ils au début d'une partie ?", options: ["Du Battle Bus", "D'un avion militaire réaliste", "D'un bateau", "D'une tour fixe"], correct: 0 },
      { text: "Quelle monnaie premium achète-t-on dans la boutique ?", options: ["V-Bucks", "Robux", "COD Points", "Minecoins"], correct: 0 },
      { text: "Quelle couleur de rareté est la plus élevée (classique) ?", options: ["Légendaire (orange)", "Commun (gris)", "Peu commun (vert)", "Rare (bleu)"], correct: 0 },
      { text: "Quel élément ferme progressivement la carte ?", options: ["La tempête / le storm", "Le brouillard", "La nuit", "Le volcan seulement"], correct: 0 },
      { text: "Quel matériau ne sert PAS à construire ?", options: ["Béton armé", "Bois", "Pierre", "Métal"], correct: 0 },
      { text: "Comment appelle-t-on une victoire en solo ?", options: ["Victory Royale", "Championnat FIFA", "Ace", "Nuke"], correct: 0 },
      { text: "Quel mode retire la construction pour se concentrer sur le tir ?", options: ["Zero Build", "Creative seulement", "Save the World", "Team Rumble classique"], correct: 0 },
      { text: "Quel était le mode coopératif original de Fortnite avant le BR ?", options: ["Save the World", "Arena", "Blitz", "Ranked Zero"], correct: 0 },
    ],
  },
];
